base: '%env(SITE_BASE)%'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
    websiteTitle: ''
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    map:
      /: 0
      sitemap.xml: 1533906435
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nDisallow: /content-examples/\r\nDisallow: /en/content-examples/\r\n# Keine Backups \r\nDisallow: *.tar.gz\r\nDisallow: *.sql\r\nDisallow: *.sql.gz\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\n"
  -
    route: sitemap.xml
    type: uri
    source: 't3://page?uid=1&type=1533906435'
websiteTitle: ''
